### ISSUE TITLE
Suggestion: better explanation of file layout requirements

### ISSUE THREAD

**Issue by einso** [rsn8887/OpenRCT2#1]
In the readme/release notes, it says "just use any working rct2 install". This doesn't work, as tested with the Discord release for RCT2. That release uses the .exe next to a GAME folder. The error log helps, but maybe mention that you have to put the folders next to the exe, as not every release is like that.

**Comment by rsn8887** [comment]
How did you get it to work? For me the rct2.exe must be here: /switch/openrct2/rct2/rct2.exe and all the other folders from the game also in that folder. So that’s how I explained it.

Was it different for you?

The requirements should be the same as for the windows version of openrct2.

I will update the release notes in an hour.

**Comment by rsn8887** [comment]
Ok I updated the instructions to make it clear where the ObjData and Landscapes and other folders should be.
